// Governing specification: Doc 08 — Frontend Architecture (QH-008 v1.0)
// Component Standards: shared design-system components re-exported here — Doc 08 §Component Standards
// No duplicated UI implementations; feature-specific components stay inside feature dirs — Doc 08 §Component Standards
// Per Doc 00 §14.11
// SidebarNav removed — navigation moved to the horizontal TopBar (owner request).
export { TopBar, PRIMARY as PRIMARY_NAV, OVERFLOW as OVERFLOW_NAV } from './TopBar'
export type { NavItem } from './TopBar'
export { ContextPanel } from './ContextPanel'
export { Button } from './Button'
export type { ButtonVariant, ButtonSize } from './Button'
export { Card, CardHeader, CardTitle, CardContent, glassSurface, CARD_RADIUS } from './Card'
export type { Elevation } from './Card'
export { Badge, pnlBadgeVariant } from './Badge'
export type { BadgeVariant } from './Badge'
export { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from './Table'
export { InstitutionalTable } from './InstitutionalTable'
export type { InstitutionalColumnDef, InstitutionalColumnMeta, ResponsiveTier } from './InstitutionalTable'
export { Tabs } from './Tabs'
export type { TabItem } from './Tabs'
export { LoadingState, EmptyState, ErrorState } from './States'
// Redesign additions (owner visual-design + feature push)
export { PageHeader } from './PageHeader'
export { Section } from './Section'
export { Stat, StatCard } from './Stat'
export { Skeleton, SkeletonTable, SkeletonStats } from './Skeleton'
export { Ring } from './Ring'
export { Sparkline } from './Sparkline'
export { LineChart } from './LineChart'
export type { LinePoint } from './LineChart'
export { MultiLineChart } from './MultiLineChart'
export type { Series } from './MultiLineChart'
export { Histogram } from './Histogram'
// ECharts-backed analytics charts (handbook/ui Doc 01 frozen engine)
export { Chart } from './Chart'
export type { ChartProps } from './Chart'
export { useChartTheme } from './chart-theme'
export type { ChartTheme } from './chart-theme'
export { DonutChart } from './DonutChart'
export type { DonutSlice } from './DonutChart'
export { Heatmap } from './Heatmap'
export { Gauge } from './Gauge'
export { Panel } from './Panel'
export { CryptoIcon } from './CryptoIcon'
export { ComingSoon } from './ComingSoon'
export { Modal } from './Modal'
export { Tooltip, TooltipProvider } from './Tooltip'
export { CommandPalette } from './CommandPalette'
